### ISSUE TITLE
`ablog start` errors out with AttributeError on sphinx.util.texescape

### ISSUE THREAD

**Issue by louy2** [sunpy/ablog#107]
### Expected vs Actual behavior

Expected:

Blog files properly created.

Actual:

```
Please enter the base URL for your project. Blog feeds will be generated
relative to this URL. If you don't have one yet, you can set it in configuration
file later.
> Base URL for your project: 

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ablog/bin/ablog", line 10, in <module>
    sys.exit(ablog_main())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ablog/lib/python3.9/site-packages/ablog/commands.py", line 448, in ablog_main
    namespace.func(**namespace.__dict__)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ablog/lib/python3.9/site-packages/ablog/start.py", line 650, in ablog_start
    generate(d)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ablog/lib/python3.9/site-packages/ablog/start.py", line 481, in generate
    ).translate(texescape.tex_escape_map)
AttributeError: module 'sphinx.util.texescape' has no attribute 'tex_escape_map'
```

### Steps to Reproduce

```zsh
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install ablog
ablog start
```

### System Details

- SunPy Version: N/A
- Astropy Version: N/A
- Python Version: 3.9.5
- OS information: macOS Big Sur 11.4 on Apple M1

**Comment by nabobalis** [comment]
Can you tell me what version of ablog and sphinx you have installed?

**Comment by louy2** [comment]
ablog: 0.9.5
Sphinx: 3.5.3

**Comment by nabobalis** [comment]
Can you try updating to ablog 0.10 (``conda update ablog`` should work)? I don't support older versions ablog anymore.

In theory nothing should break.

**Comment by louy2** [comment]
`conda update ablog` still gives me 0.9.5.

```
conda install ablog~=0.10 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                      

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
Note that strict channel priority may have removed packages required for satisfiability.
```

**Comment by nabobalis** [comment]
Can you do `conda search ablog`?

**Comment by louy2** [comment]
```
conda search ablog                      
Loading channels: done
# Name                       Version           Build  Channel             
ablog                          0.9.2            py_0  conda-forge         
ablog                          0.9.2            py_1  conda-forge         
ablog                          0.9.3            py_0  conda-forge         
ablog                          0.9.4            py_0  conda-forge         
ablog                          0.9.5            py_0  conda-forge         
ablog                         0.10.8    pyh9f0ad1d_0  conda-forge         
ablog                         0.10.9    pyh9f0ad1d_0  conda-forge         
ablog                        0.10.10    pyh9f0ad1d_0  conda-forge         
ablog                        0.10.11    pyh9f0ad1d_0  conda-forge         
ablog                        0.10.12    pyhd3deb0d_0  conda-forge         
ablog                        0.10.13    pyh44b312d_0  conda-forge         
ablog                        0.10.14    pyhd8ed1ab_0  conda-forge         
ablog                        0.10.15    pyhd8ed1ab_0  conda-forge         
ablog                        0.10.16    pyhd8ed1ab_0  conda-forge         
ablog                        0.10.17    pyhd8ed1ab_0  conda-forge         
ablog                        0.10.18    pyhd8ed1ab_0  conda-forge         
ablog                        0.10.19    pyhd8ed1ab_0  conda-forge 
```

**Comment by nabobalis** [comment]
So it finds them but it won't install ablog? 

How about `conda install ablog=0.10.19`?

**Comment by louy2** [comment]
Same error as `conda install ablog~=0.10`. I know right, it's so weird. Maybe it's `conda` bug?

**Comment by nabobalis** [comment]
It might be due to the Apple M1? I am not really sure how anaconda deals with arm chips.

**Comment by louy2** [comment]
Maybe a dependency in the tree of 0.10 doesn't have Apple M1 package?

**Comment by nabobalis** [comment]
Possible. You could try pip installing it but mixing conda and pip packages isn't great.

**Comment by louy2** [comment]
Yeah. `pip install ablog` succeeded, but installing `pandas` et al via `pip` is a struggle on Apple M1.

I think we can close this since this is more a conda problem.

**Comment by nabobalis** [comment]
I am not sure who to contact upstream on conda or conda forge to ask. 

These are the packages the recipe tries to install. Could try to find which one doesnt install.
``
- sphinx >=2.0
- invoke
- docutils
- python-dateutil
- watchdog
- feedgen
- nbsphinx
- pandoc
- myst-parser
```

**Comment by louy2** [comment]
Using `mamba` gave me the crucial information:

```
mamba install ablog~=0.10

...

Encountered problems while solving:
  - nothing provides pandoc needed by ablog-0.10.10-pyh9f0ad1d_0
```

**Comment by nabobalis** [comment]
That is good to know! 

You might have to see if there is an issue on pandoc's conda-forge feedstock to add a supported version.
